kind: Service
apiVersion: v1
metadata:
  name: lmz-test-es
  namespace: test
  labels:
    k8s-app: lmz-test-es
spec:
  selector:
    k8s-app: lmz-test-es
  clusterIP: None
  ports:
    - port: 9200
      name: rest
    - port: 9300
      name: inter-node
