apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: cnvrg.io/ifs
  creationTimestamp: "2021-03-04T15:44:59Z"
  deletionGracePeriodSeconds: 0
  deletionTimestamp: "2021-03-27T13:59:33Z"
  finalizers:
  - kubernetes.io/pv-protection
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        f:phase: {}
    manager: kube-controller-manager
    operation: Update
    time: "2021-03-04T15:44:59Z"
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:pv.kubernetes.io/provisioned-by: {}
      f:spec:
        f:accessModes: {}
        f:capacity:
          .: {}
          f:storage: {}
        f:claimRef:
          .: {}
          f:apiVersion: {}
          f:kind: {}
          f:name: {}
          f:namespace: {}
          f:resourceVersion: {}
          f:uid: {}
        f:nfs:
          .: {}
          f:path: {}
          f:server: {}
        f:persistentVolumeReclaimPolicy: {}
        f:storageClassName: {}
        f:volumeMode: {}
    manager: nfs-subdir-external-provisioner
    operation: Update
    time: "2021-03-04T15:44:59Z"
  name: pvc-5c6be434-6d8c-4a0e-9e58-5da2238f5ca8
  resourceVersion: "18124748"
  uid: 7a7a7ff3-4dd7-41e8-a6f2-f43be44a7ec5
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 15Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: elasticsearch-logging-elasticsearch-logging-0
    namespace: kube-logging
    resourceVersion: "2610823"
    uid: 5c6be434-6d8c-4a0e-9e58-5da2238f5ca8
  nfs:
    path: /home/lzuccarelli/srv/nfs4/kube-logging-elasticsearch-logging-elasticsearch-logging-0-pvc-5c6be434-6d8c-4a0e-9e58-5da2238f5ca8
    server: 192.168.1.29
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-storage
  volumeMode: Filesystem
status:
  phase: Bound
